services:
  db:
    build:
      target: db
    image: ${PROJECT_NAME}/db
    container_name: db
    restart: unless-stopped
    volumes:
      - ./config/logs/sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - wp_net

  wp:
    build:
      target: wp
    image: ${PROJECT_NAME}/wp
    container_name: wp
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}:${DB_PORT}"
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${DB_TABLE_PREFIX}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME','https://localhost.test' );
        define( 'WP_SITEURL','https://localhost.test' );
        define( 'FS_METHOD', 'direct' );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        @ini_set( 'display_errors', 0 );
        define( 'POST_REVISIONS', false );
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_CACHE', true );
        define( 'WP_MEMORY_LIMIT', '256M' );
        define( 'FORCE_SSL_ADMIN', true );
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - db
    networks:
      - wp_net

  nginx:
    build:
      target: server
    image: ${PROJECT_NAME}/nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html:ro
      - ./config/logs/nginx:/var/log/nginx
      - ./config/snippets:/etc/nginx/snippets
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wp
    networks:
      wp_net:
        aliases:
          - localhost.test

volumes:
  wp_data:

networks:
  wp_net:
    driver: bridge
